//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Key]
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public System.DateTime HireDate { get; set; }
        public string ContactInfo { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
