//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Maintenance_Record
    {
        [Key]
        public int BusID { get; set; }
        public System.DateTime MaintenanceDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
