//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reserve
    {
        [Key]
        public int PassengerID { get; set; }
        public int TripID { get; set; }
        public int TicketID { get; set; }
        public int SeatNumber { get; set; }
        public decimal PricePaid { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
