//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Route_Stop_Assignment
    {
        [Key]
        public int RouteID { get; set; }
        public int StopID { get; set; }
        public int StopOrder { get; set; }
    
        public Route Route { get; set; }
        public  Stop Stop { get; set; }
    }
}
